# Generated by Django 5.0.6 on 2024-07-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_room', '0002_room_number_alter_room_capacity_alter_room_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='created_at',
            new_name='booking_date',
        ),
    ]
