# Generated by Django 5.0.6 on 2024-07-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pastorder_pastorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastorderitem',
            name='past_order',
        ),
        migrations.RemoveField(
            model_name='pastorderitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='PastOrder',
        ),
        migrations.DeleteModel(
            name='PastOrderItem',
        ),
    ]
