# Generated by Django 5.0.6 on 2024-07-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_pastorderitem_past_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='images',
            new_name='image',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
