# Generated by Django 5.0.6 on 2024-07-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_cartitem_cart_remove_cartitem_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
    ]
